# Generated by Django 5.2.13 on 2026-06-16 07:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0012_alter_staff_monthly_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='monthly_target',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='staff',
            name='phone',
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
