# Generated by Django 5.2.13 on 2026-07-09 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0004_alter_course_duration'),
        ('student_attendance', '0002_alter_batch_batch_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('', 'Select Status'), ('Present', 'Present'), ('Absent', 'Absent'), ('Late', 'Late')], max_length=10),
        ),
        migrations.CreateModel(
            name='AbsentTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_absences', models.IntegerField(default=0)),
                ('consecutive_absences', models.IntegerField(default=0)),
                ('attendance_percentage', models.FloatField(default=100)),
                ('alert_level', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('Critical', 'Critical')], default='Low', max_length=10)),
                ('observation_notes', models.TextField(blank=True, null=True)),
                ('notification_status', models.CharField(choices=[('SMS Pending', 'SMS Pending'), ('Dispatched', 'Dispatched')], default='SMS Pending', max_length=20)),
                ('attendance_status', models.CharField(default='Complete', max_length=20)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('notification_sent', models.BooleanField(default=False)),
                ('last_notified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admissions.enrollment')),
            ],
        ),
    ]
