# Generated by Django 5.2.16 on 2026-07-13 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0014_alter_staff_monthly_target'),
        ('student_attendance', '0003_alter_attendance_status_absenttracker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='trainer',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__role_name': 'Trainer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.staff'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='trainer',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__role_name': 'Trainer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.staff'),
        ),
        migrations.AlterField(
            model_name='syllabuslog',
            name='trainer',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__role_name': 'Trainer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='syllabus_logs', to='staff.staff'),
        ),
    ]
