# Generated by Django 5.2.13 on 2026-06-05 07:27

import cloudinary.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=20)),
                ('course_fee', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))])),
                ('mode', models.CharField(choices=[('UPI', 'UPI'), ('CASH', 'Cash'), ('CARD', 'Card')], max_length=10)),
                ('reference_id', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('PENDING', 'Pending'), ('FAILED', 'Failed')], default='SUCCESS', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Only alphabets and spaces are allowed.', regex='^[A-Za-z ]+$')])),
                ('last_name', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Only alphabets and spaces are allowed.', regex='^[A-Za-z ]+$')])),
                ('dob', models.DateField()),
                ('phone_no', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits.', regex='^\\d{10}$')])),
                ('gender', models.CharField(choices=[('', 'Select Gender'), ('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a proper email (example: name@gmail.com)', regex='^[\\w\\.-]+@[\\w\\.-]+\\.\\w+$')])),
                ('address', models.TextField()),
                ('guardian_name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Only alphabets and spaces are allowed.', regex='^[A-Za-z ]+$')])),
                ('guardian_phone_no', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits.', regex='^\\d{10}$')])),
                ('photo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='student_photos/')),
                ('id_proof', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='id_proofs/')),
                ('certificate', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='certificates/')),
            ],
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('enquiry', 'Enquiry'), ('confirmed', 'Confirmed'), ('enrolled', 'Enrolled'), ('dropped', 'Dropped')], default='enquiry', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admissions.course')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('payment_status', models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending'), ('Partial', 'Partial')], default='Pending', max_length=20)),
                ('admission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment', to='admissions.admission')),
            ],
        ),
    ]
