# Generated by Django 5.2.13 on 2026-06-05 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admissions', '0001_initial'),
        ('student_attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='student_attendance.batch',null=True,
        blank=True,),
        ),
        migrations.AddField(
            model_name='payment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='admissions.student'),
        ),
        migrations.AddField(
            model_name='admission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='admissions.student'),
        ),
        migrations.AddConstraint(
            model_name='admission',
            constraint=models.UniqueConstraint(fields=('student', 'course_name'), name='unique_student_course'),
        ),
    ]
