# Generated by Django 5.2.13 on 2026-06-08 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_initial'),
        ('student_attendance', '0002_alter_batch_batch_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='student_attendance.batch'),
        ),
    ]
