# Generated by Django 5.2.13 on 2026-07-15 10:27

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0004_alter_course_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='certificate',
        ),
        migrations.RemoveField(
            model_name='student',
            name='id_proof',
        ),
        migrations.CreateModel(
            name='StudentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('id_proof', 'ID Proof'), ('certificate', 'Certificate')], max_length=20)),
                ('document', cloudinary.models.CloudinaryField(max_length=255, verbose_name='student_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='admissions.student')),
            ],
        ),
    ]
